language: cpp

notifications:
  email: false

branches:
  only:
    - master
    - stable

before_install:
  - source travis_pre_build.sh

install:
  - make

script:
  - cd drake/pod-build
  - ctest -j 1 -D Experimental -C $BUILD_TYPE --output-on-failure --timeout 1000 --track Continuous

# The compiler and env:matrix options create an matrix of build configurations (gcc + Release, gcc + Debug, clang + Release, clang + Debug)

python:
  - '2.7'

matrix:
  include:
    - sudo: required
      os: linux
      dist: precise
      compiler: clang
      env: BUILD_TYPE=Release
    - sudo: required
      os: linux
      dist: precise
      compiler: gcc
      env: BUILD_TYPE=Release
    - sudo: required
      os: linux
      dist: precise
      compiler: clang
      env: BUILD_TYPE=Debug
    - sudo: required
      os: linux
      dist: trusty
      compiler: gcc
      env: BUILD_TYPE=Release
    - sudo: required
      os: osx
      compiler: clang
      env: BUILD_TYPE=Release

